import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Marika",
      email: "marika@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Piotr",
      email: "piotr@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Cuni Adult Complete - pokarm dla królików",
      category: "rabbits",
      image: "/images/VL_cuni_adult_complete_175.jpg",
      price: 59,
      countInStock: 10,
      brand: "Versele Laga",
      rating: 4.5,
      numReviews: 10,
      description: "Wysokiej jakości granulat dla dorosłych królików",
    },
    {
      name: "Cuni Junior Complete - pokarm dla królików",
      category: "rabbits",
      image: "/images/VL_cuni_junior_complete_175.jpg",
      price: 62,
      countInStock: 20,
      brand: "Versele Laga",
      rating: 4.5,
      numReviews: 10,
      description: "Wysokiej jakości granulat dla młodych królików",
    },
    {
      name: "Cavia Complete - pokarm dla kawii domowej",
      category: "rodents",
      image: "/images/VL_cavia_complete_175.jpg",
      price: 59,
      countInStock: 15,
      brand: "Versele Laga",
      rating: 4.5,
      numReviews: 10,
      description: "Wysokiej jakości granulat dla dorosłych świnek morskich",
    },
    {
      name: "Chinchila Complete - pokarm dla szynszyli",
      category: "rodents",
      image: "/images/VL_chinchila_complete_175.jpg",
      price: 59,
      countInStock: 7,
      brand: "Versele Laga",
      rating: 4.5,
      numReviews: 10,
      description: "Wysokiej jakości granulat dla szynszyli",
    },
    {
      name: "Rat Complete - pokarm dla szczurów",
      category: "rodents",
      image: "/images/VL_rat_complete_700.png",
      price: 18.9,
      countInStock: 0,
      brand: "Versele Laga",
      rating: 4.3,
      numReviews: 10,
      description: "Wysokiej jakości granulat dla szczurów",
    },
    {
      name: "Rat Complete - pokarm dla szczurów",
      category: "rodents",
      image: "/images/VL_rat_complete_700.png",
      price: 18.9,
      countInStock: 0,
      brand: "Versele Laga",
      rating: 4.3,
      numReviews: 10,
      description: "Wysokiej jakości granulat dla szczurów",
    },
    {
      name: "Rat Complete - pokarm dla szczurów",
      category: "rodents",
      image: "/images/VL_rat_complete_700.png",
      price: 18.9,
      countInStock: 0,
      brand: "Versele Laga",
      rating: 4.3,
      numReviews: 10,
      description: "Wysokiej jakości granulat dla szczurów",
    },
  ],
};

export default data;
